"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[jobs]
symbol = '+ '

[package]
disabled = true

[golang]
symbol = '󰟓 '

[rust]
symbol = ' '
format = '[$symbol$version ](red bold)'

[cmd_duration]
format = '[$duration]($style) '

[c]
disabled = true

[cpp]
disabled = true

[python]
symbol = ' '
format = '[$symbol$version ]($style)'

[ocaml]
symbol = ' '
format = '[$symbol$version ]($style)'

[lua]
symbol = ' '
format = '[$symbol$version ]($style)'
